name: publish

on:
  push:
    tags: [ v* ]

jobs:
  build-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Restore
      run: |
        dotnet restore NewLife.RocketMQ/NewLife.RocketMQ.csproj
    - name: Build
      run: |
        dotnet pack --no-restore --version-suffix $(date "+%Y.%m%d") -o out NewLife.RocketMQ/NewLife.RocketMQ.csproj
    - name: Publish
      run: |
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/NewLifeX/index.json --api-key ${{ github.token }}
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nugetKey }}
